export const REPOSITORIES_LOADING = 'REPOSITORIES_LOADING';
export const REPOSITORIES_FAILED = 'REPOSITORIES_FAILED';
export const ADD_REPOSITORIES = 'ADD_REPOSITORIES';
export const SORT_REPOSITORIES_STARS = 'SORT_REPOSITORIES_STARS';