export const REPOSITORIES_LOADING = 'REPOSITORIES_LOADING';
export const REPOSITORIES_FAILED = 'REPOSITORIES_FAILED';
export const ADD_REPOSITORIES = 'ADD_REPOSITORIES';
export const ADD_MORE_REPOSITORIES = 'ADD_MORE_REPOSITORIES';
export const MORE_REPOSITORIES_LOADING = 'MORE_REPOSITORIES_LOADING';
export const SORT_REPOSITORIES_STARS = 'SORT_REPOSITORIES_STARS';
export const SORT_REPOSITORIES_FORK = 'SORT_REPOSITORIES_FORK';
export const FILTER_REPOSITORIES_LANGUAGE = 'FILTER_REPOSITORIES_LANGUAGE';

export const REPOSITORY_BRANCHES_LOADING = 'REPOSITORY_BRANCHES_LOADING';
export const REPOSITORY_BRANCHES_FAILED = 'REPOSITORY_BRANCHES_FAILED';
export const ADD_REPOSITORY_BRANCHES = 'ADD_REPOSITORY_BRANCHES';

export const ORGANIZATION_LOADING = 'ORGANIZATION_LOADING';
export const ORGANIZATION_FAILED = 'ORGANIZATION_FAILED';
export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';